# Generated by Django 5.2.15 on 2026-06-25 06:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(max_length=100)),
                ('price_numeric', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(default='Lahore', max_length=100)),
                ('phase', models.CharField(blank=True, db_index=True, max_length=100)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=10)),
                ('category', models.CharField(choices=[('Residential Plots', 'Residential Plots'), ('Commercial Plots', 'Commercial Plots'), ('Houses', 'Houses'), ('Apartments', 'Apartments'), ('Villas', 'Villas'), ('Files', 'Files')], default='Residential Plots', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('images', models.JSONField(blank=True, default=list)),
                ('main_image', models.CharField(blank=True, max_length=500)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='agents.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
